# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
